import './globals.css'
import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import localFont from 'next/font/local'
import NavBar from './NavBar'
import AuthProvider from './auth/Provider'
import { Session } from 'inspector'
import GoogleAnalyticsScript from './GoogleAnalyticsScript'
import { Body } from '@react-email/components'

const inter = Inter({ subsets: ['latin'] })

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['900', '900']
})

const dialogue = localFont({
  src: '../public/fonts/Dialogue.otf',
  variable: '--font-Dialogue',
  weight: '2000'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  // openGraph: {
  //   title: '...',
  //   description: '...'
  // }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="winter">
      <GoogleAnalyticsScript />
      {/* <body className={dialogue.className}> */}
      {/* <body className={admiration.variable}> */}
      <body>
        <AuthProvider>
          <NavBar />
          <main className='p-5'>
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  )
}
